### PR TITLE
Fix timezone mistakes in application migration

### PR DESCRIPTION
**Pull request by matti-lamppu**
## 🛠️ Changelog
[//]: # "Describe the changes in this pull request here."

- Fix mistakes in using timezones for `datetime.time` objects. These should be naive.

## 🧪 Test plan
[//]: # "Help your fellow reviewer and write a short description of the fastest way to test your changes."

- Automated tests

## 🚧 Dependencies
[//]: # "Is this PR dependent on other changes outside this repository? Describe the changes, or add links to them."
[//]: # "e.g. This PR breaks X and is waiting for frontend changes before merging."

- None

### CODE REVIEW

**Comment by matti-lamppu** [comment]
Checked that the fast forward action does not allow fast forward before branch protection rules are met

**Review by joonatank — APPROVED** [review]

**Pull request merged**
