### PR TITLE
Add SQL logging

### PR DESCRIPTION
**Pull request by matti-lamppu**
## 🛠️ Changelog
[//]: # "Describe the changes in this pull request here."

Adds SQL logging middleware.

This middleware can be used for logging SQL queries made to the backend in any HTTP request. This information can then be used to make sure the queries are optimized, which queries are most used, how long do the queries take, which queries require indexes, etc.

The middleware is off by default and can must be turned on with the `QUERY_LOGGING_ENABLED` env variable. The logger can be further tuned with the `QUERY_LOGGING_SKIP_ROUTES` setting to skip logging for some routes (e.g. `/admin` to not log any admin requests).

Logs are saved at the end of the request using a celery task, which is handled by the celery worker in production. This should make sure that the impact of saving logs for each request is minimal.

## 🧪 Test plan
[//]: # "Help your fellow reviewer and write a short description of what's the fastest way to test your changes."

The middleware can be tested locally by setting the `QUERY_LOGGING_ENABLED` env variable to `True` and the `CELERY_TASK_ALWAYS_EAGER = True` in `local_settings.py`. After this, logs should start generating for all requests. The admin panel should contain a section for "SQL logs", where the logs can be filtered further for analysis. Further development for processing the logs can be done in the future.

### CODE REVIEW

**Comment by vergama** [comment]
Saving the request body without obfuscation might be a problem in production env.
Since they are in practice JSON data for GQL, maybe masking `variables` part would be sufficient?
(And the body simply not included in the logged data, if the request doesn't parse like that.)

**Comment by matti-lamppu** [comment]
@vergama Changed logging so that the body is only captured for GraphQL requests, and only the query part is parsed out. This should remove any mutation variables from the logs.

**Review by vergama — APPROVED** [review]
Nice

**Review by ranta — APPROVED** [review]
Nice!
Might be also good to add `QUERY_LOGGING_ENABLED=false` to `.env.example`

**Comment by matti-lamppu** [comment]
Merged PRs #1155, #1160, #1157, and #1177 to this PR so that they can be merged to main together.

**Pull request merged**
