### PR TITLE
increase unit query complexity for frontend

### PR DESCRIPTION
**Pull request by joonatank**
## 🛠️ Changelog
[//]: # "Describe the changes in this pull request here."

- Frontend PR https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1184 unit query added a field and requires higher complexity.

## 🧪 Test plan
[//]: # "Help your fellow reviewer and write a short description of the fastest way to test your changes."

- Automated tests

## 🚧 Dependencies
[//]: # "Is this PR dependent on other changes outside this repository? Describe the changes, or add links to them."
[//]: # "e.g. This PR breaks X and is waiting for frontend changes before merging."

- None

## 🎫 Tickets
[//]: # "This pull request resolves all or part of the following ticket(s)."

- [TILA-][TILA]

[TILA]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-

### CODE REVIEW

**Comment by matti-lamppu** [comment]
@joonatank Do you need this in `main`, or can it be added to the tail of our merge queue? (i.e. #1216)

**Comment by joonatank** [comment]
Need it after [BE#1178](https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1178). The next one in queue is the frontend change that requires it. Or have to delay the frontend PR merge.

**Review by matti-lamppu — APPROVED** [review]

**Pull request merged**
