### PR TITLE
TILA-1332 | Add unit filter to application rest end point

### PR DESCRIPTION
**Pull request by nicobav**
TILA-1332

### CODE REVIEW

**Review by Niilis — COMMENTED** [review]
Code looks good but test seems to be failing. :thinking:

**Comment by nicobav** [comment]
> Code looks good but test seems to be failing. thinking

Yes, there's some stupid mistake by me within in the test :disappointed:  I'll fixit

**Comment by nicobav** [comment]
Fixed :magic_wand:

**Review by Niilis — APPROVED** [review]
All good now! :100:

**Pull request merged**
