### PR TITLE
TILA-2346 | Add viewer user's name and email to PersonalInfoViewLog

### PR DESCRIPTION
**Pull request by nicobav**
## Change log
- Add viewer's full name and email to PersonalInfoViewLog
 - Add task for removing old PersonalInfoViewLogs

## TODO
- [ ] Add the task to envs after merge

Refs TILA-2346 TILA-2347

### CODE REVIEW

**Comment by nicobav** [comment]
Really hard to write specific tests for those migrations.. They're tested in a way in every usage of the field which are tested obviously. Would need tweak the coverage to exclude migrations perhaps.

**Review by vergama — COMMENTED** [review]
Removal test could check that logs newer than time limit are retained. Limit is 2 years, not 1.

**Comment by nicobav** [comment]
> Removal test could check that logs newer than time limit are retained. Limit is 2 years, not 1.

Nice catch! There's something to change there 👍

**Comment by nicobav** [comment]
Changed the deletion threshold to two years 😇

**Review by vergama — APPROVED** [review]

**Review by saaste — APPROVED** [review]
Good stuff!

**Pull request merged**
