### PR TITLE
Change reservation unit search from Elastic to Postgres FTS

### PR DESCRIPTION
**Pull request by matti-lamppu**
## 🛠️ Changelog
[//]: # "Describe the changes in this pull request here."

- Change reservation unit search from ElasticSearch to Postgres FTS and remove ElasticSearch from the project
- Text search is now language-specific depending on the users preferred language, or request language for unauthenticated users
- Additional "search terms" (="hakusanat") can be added to reservation units with the admin panel or via the GraphQL API to make sure reservation unit is shown using a specific search term regardless of the UI language (e.g. "omatoimisesti")
- For speed, text search vectors are pre-calculated (for all languages) to the reservation units when relevant data changes. This is done with signals and a scheduled background job (needs to be scheduled when in production)
- Additionally, we make a containment search (`__icontains` = `LIKE`) for reservation unit's name to allow postfix matching (e.g. "room" would match "workroom" or "bathroom"). This is ommitted for other fields for speed.
- Search is now able to handle _some_ different grammatical cases, but it's not 100% accurate
  - e.g. "pukimäki" does not match "pukinmäen" but "pukinmäessä" does

## 🧪 Test plan
[//]: # "Help your fellow reviewer and write a short description of the fastest way to test your changes."

- Automated tests

## 🚧 Dependencies
[//]: # "Is this PR dependent on other changes outside this repository? Describe the changes, or add links to them."
[//]: # "e.g. This PR breaks X and is waiting for frontend changes before merging."

- None

## 🎫 Tickets
[//]: # "This pull request resolves all or part of the following ticket(s)."

- [TILA-3046](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3046)

[TILA-3046]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by vergama** [comment]
Sounds very tasty.

**Comment by vergama** [comment]
If _unit_ name happens to change in Toimipisterekisteri (a rare occurrence if ever), I guess that possibility can be conveniently taken care of by scheduling the background job so that it is run (at least) after the nightly TPR update task.

**Comment by matti-lamppu** [comment]
@vergama We need to have some "backup update" in place anyway since signals don't fire on bulk updates.

**Review by ranta — APPROVED** [review]
🔍🚀

**Pull request merged**
